#!/bin/bash
set -euo pipefail

# note: if performance of your Linux computer is bad
# you might get a lot of mutants killed by timeout!
#
# in this example, not a single test should fail because of timeout!

# remove .stryker-tmp - just so that we have an easier time showing exactly the code of the last run
rm -rf .stryker-tmp

npm run mutation-test
